### PR TITLE
[CLOUD-2251] - Produce Intelligent Process Server and Realtime Decisi…

### PR DESCRIPTION
**Pull request by spolti**
…on Server Images with EAP 7

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by rcernich** [comment]
I believe this should be a separate image.yaml, possibly on a different branch.  Once this change is incorporated, there will be no process server 6.4 on eap 6.4.

**Comment by spolti** [comment]
The PR is targeting this branch: https://github.com/jboss-container-images/jboss-decisionserver-6-openshift-image/tree/decisionserver64-eap7-dev

**Comment by rcernich** [comment]
Thanks @spolti.  I should have spotted that.  Sorry.

**Review by rcernich — APPROVED** [review]

**Comment by spolti** [comment]
No worries Rob, thanks for reviewing it.

**Review by errantepiphany — APPROVED** [review]
LGTM

**Pull request merged**
